### ISSUE TITLE
Doesn't work both in `layout.tsx` and `page.tsx` (Next.js 14)

### ISSUE THREAD

**Issue by maral** [manvalls/server-only-context#2]
Hi, first of all thanks for this simple yet very useful package. When playing with this in our Next.js 14 project, I found out that `layout.tsx` and `page.tsx` are most likely run in a separate context, so there is no sharing of server side context via this package. Minimal example:

`context.ts`
```ts
import serverContext from 'server-only-context';

export const [getUserId, setUserId] = serverContext('')
```

`layout.tsx`:
```ts
import { setUserId } from '@/context'

export default function Layout() {
  // retrieve userId somehow
  const userId = 'john';

  setUserId(userId)
  return <MyComponent/>
}
```

`someComponentImportedFromPage.tsx`
```ts
import { getUserId } from '@/context'

export default function MyComponent() {
  const userId = getUserId()

  return (
    <div>
      Hello {userId}!.
    </div>
  )
}
```

Same goes for the other direction, when you set user ID in the `page.tsx` and try to use it in the `layout.tsx` or its imported components.

Would be great if someone could confirm the same behavior on their side. And if it holds, I suggest adding a note about this behavior to the README. The solution here is to set the user ID in both roots (`layout.tsx` and `page.tsx`). I haven't explored the other special files (like `loading.tsx` etc.). Probably the cleanest thing is to box it into a component (something like `ServerContextProviders`) and use this component in all layouts and pages.

**Comment by maral** [comment]
Okay never mind, after further testing I disproved this hypothesis. 😆 It works when I set it either `layout.tsx` or `page.tsx`. Not sure what the problem was before.

**Comment by manvalls** [comment]
Hey @maral , when doing client side navigation, it is possible that the layout is reused, so if you set your context in the layout, it won't work, so yeah, you need to set it in both places. I'll add it to the readme.

**Comment by mkbctrl** [comment]
I think I know what could happen to you @maral 
In my case I have a layout under: `[slug]/layout.tsx` and a `[slug]/page.tsx`, and when I am setting the values within the layout, here is the execution order:

```
{"level":30,"time":1706392634701,"pid":30249,"hostname":"mkbctrlnn.local","userId":null,"eventId":null,"msg":"Server context in nested server component "}

setting the values
```

Layout was my go to place, as I have queries already there.

If you load the data through page, then the order of execution is correct. I will leave it here for anyone else wondering how to debug the problem.

@manvalls thanks a lot for that library 🍻

**Comment by dreamawakening** [comment]
Not sure if this is a separate issue, but I'm having trouble sharing data from a page with a separate layout. 

My page sets state using `server-only-context` in a page. Then the layout fetches the same state.

The problem is the layout runs before the page that sets the state, so when it fetches it, it hasn't been set yet. So it can never access the value.

How do I get the timing to work, so that the layout will only access the value *after* it's been set inside the page?

**Comment by maral** [comment]
Hi @demeralde, I believe this is an issue with the RSC implementation in Next.js or elsewhere you're using it. I adopted the same technique as `server-only-context` is using and it worked in Next.js 14.0 - I had the context placed in `layout.tsx` and both page.tsx and layout.tsx descdendants had the data.

After upgrading to 14.1 the `page.tsx` stopped receiving the data from `layout.tsx`. In the end I think the meta-framework creators have to provide this, as it's a common use case and currently it depends entirely on their implementation which keeps changing. And we really need this functionality on several places.

**Comment by manvalls** [comment]
Page and layout should be treated as having independent context, to stay on the safe side set the context data on both places

**Comment by dreamawakening** [comment]
Oof, hopefully this gets addressed soon by the Next team and there's a native solution
