### ISSUE TITLE
This package breaks our CLI scripts

### ISSUE THREAD

**Issue by maral** [manvalls/server-only-context#3]
We have a CLI script that reads all components and extracts some of their properties (and stores them somewhere). However, this currently throws this error, wherever we use `server-only-context` or a function that imports it:
```
❌ Error: This module cannot be imported from a Client Component module. It should only be used from a Server Component.
```

One possibility to go around this is to use the package [server-cli-only](https://www.npmjs.com/package/server-cli-only) instead of `server-only`.

**Comment by manvalls** [comment]
I've removed the `server-only` import. Mind you, `cache` isn't implemented in client components for the time being.

I haven't tested `server-cli-only`, but from looking at its code, I'm not sure it would prevent client components from using this package when rendering on the server with node's runtime.
